version: '3'

volumes:
  local_mysql_data: {}
  local_rabbitmq_data: {}

services:
  flask: &flask
    build:
      context: .
      dockerfile: ./compose/dev/Dockerfile
    image: electronic-api
    env_file:
      - ./.environments/local/.api
    ports:
      - 9005:5005
    volumes:
      - ./src:/app


