"""send

Revision ID: 04b6de18f1a6
Revises: 49cfb1bbee0b
Create Date: 2022-05-03 09:00:29.920557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04b6de18f1a6'
down_revision = '49cfb1bbee0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sendsinvoices', sa.Column('Total', sa.Float(precision=20), nullable=True, comment='total del documento'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sendsinvoices', 'Total')
    # ### end Alembic commands ###
