"""Events

Revision ID: 0771991a9404
Revises: 1cfa81e3461b
Create Date: 2022-06-04 08:55:42.293564

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0771991a9404'
down_revision = '1cfa81e3461b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('CreateDate', sa.DateTime(), nullable=True, comment='Fecha de creación'),
    sa.Column('UpdateDate', sa.DateTime(), nullable=True, comment='Fecha de Modificación'),
    sa.Column('IssuerNit', sa.String(length=20), nullable=False, comment='Nit de la empresa o emisor '),
    sa.Column('DocType', sa.String(length=5), nullable=False, comment='Tipo de Doc AD=Contenedor FV=factura NC=Nota Cr ND=Nota DB DS=Documento Soporte NOM=Nomina NOMA=Nomina Ajuste '),
    sa.Column('Prefix', sa.String(length=4), nullable=False, comment='Prefijo del documento de la empresa '),
    sa.Column('SerieNumber', sa.String(length=15), nullable=True, comment='Numero de serie de la factura'),
    sa.Column('YearSend', sa.String(length=4), nullable=False, comment='Año Envio '),
    sa.Column('NumberSend', sa.Integer(), nullable=False, comment='numero envio..reinicia cada año '),
    sa.Column('DianResolution', sa.String(length=50), nullable=True, comment='Resolucion Dian '),
    sa.Column('IdSoftware', sa.String(length=100), nullable=True, comment='id software dian '),
    sa.Column('ClientNit', sa.String(length=20), nullable=True, comment='Nit del cliente '),
    sa.Column('ClientName', sa.String(length=100), nullable=True, comment='Nombre del cliente '),
    sa.Column('DateSend', sa.DateTime(timezone=10), nullable=True, comment='Fecha Envio '),
    sa.Column('HourSend', sa.String(length=20), nullable=True, comment='Hora Envio '),
    sa.Column('DianResponse', mysql.LONGTEXT(), nullable=True, comment='Respuesta DIAN '),
    sa.Column('DianResponseErrors', mysql.LONGTEXT(), nullable=True, comment='Errores DIAN '),
    sa.Column('DianXml', mysql.LONGTEXT(), nullable=True, comment='Xml enviado a DIAN '),
    sa.Column('DianXmlAppResponse', mysql.LONGTEXT(), nullable=True, comment='Xml Respuesta DIAN '),
    sa.Column('Cufe', sa.String(length=150), nullable=True, comment='CUFE, CUDE o CUNE documento '),
    sa.Column('CUDE', sa.String(length=150), nullable=True, comment='CUDE del evento'),
    sa.Column('TrackIdDian', sa.String(length=200), nullable=True, comment='Cadena que reporta la DIAN '),
    sa.Column('JsonReceived', mysql.LONGTEXT(), nullable=True, comment='JSON serializado'),
    sa.Column('MessageEmail', mysql.LONGTEXT(), nullable=True, comment='Mensaje del estado email'),
    sa.Column('Status', sa.String(length=1), nullable=True, comment='0 Rechazado 1=Enviado '),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index('ix_idy', 'events', ['IssuerNit', 'DocType', 'YearSend'], unique=False)
    op.drop_index('ix_iddian', table_name='diandata')
    op.drop_table('diandata')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diandata',
    sa.Column('Id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('CreateDate', mysql.DATETIME(), nullable=True, comment='Fecha de creación'),
    sa.Column('UpdateDate', mysql.DATETIME(), nullable=True, comment='Fecha de Modificación'),
    sa.Column('IssuerNit', mysql.VARCHAR(length=20), nullable=False, comment='Nit de la empresa o emisor '),
    sa.Column('DianSoftwareId', mysql.VARCHAR(length=100), nullable=False, comment='id del software de la Dian '),
    sa.Column('Prefix', mysql.VARCHAR(length=5), nullable=False, comment='Prefijo'),
    sa.Column('DianPin', mysql.VARCHAR(length=5), nullable=False, comment='id del software de la Dian '),
    sa.Column('DianTestSetId', mysql.VARCHAR(length=100), nullable=True, comment='set de prueba'),
    sa.Column('DocType', mysql.VARCHAR(length=5), nullable=False, comment='Tipo de Doc AD=Contenedor FV=factura NC=Nota Cr ND=Nota DB DS=Documento Soporte NOM=Nomina NOMA=Nomina Ajuste '),
    sa.PrimaryKeyConstraint('Id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_iddian', 'diandata', ['IssuerNit', 'DocType', 'Prefix', 'DianSoftwareId'], unique=False)
    op.drop_index('ix_idy', table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
