"""Update events

Revision ID: 1734ff01c2a0
Revises: 0771991a9404
Create Date: 2022-06-16 09:36:51.261414

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1734ff01c2a0'
down_revision = '0771991a9404'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shoppings',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('CreateDate', sa.DateTime(), nullable=True, comment='Fecha de creación'),
    sa.Column('UpdateDate', sa.DateTime(), nullable=True, comment='Fecha de Modificación'),
    sa.Column('ReceiverNit', sa.String(length=20), nullable=False, comment='Nit de la persona que recibe'),
    sa.Column('DocType', sa.String(length=5), nullable=False, comment='Tipo de Doc AD=Contenedor FV=factura NC=Nota Cr ND=Nota DB DS=Documento Soporte NOM=Nomina NOMA=Nomina Ajuste '),
    sa.Column('Prefix', sa.String(length=4), nullable=False, comment='Prefijo del documento de la empresa '),
    sa.Column('SerieNumber', sa.String(length=15), nullable=True, comment='Numero de serie de la factura'),
    sa.Column('YearSend', sa.String(length=4), nullable=False, comment='Año Envio '),
    sa.Column('NumberSend', sa.Integer(), nullable=False, comment='numero envio..reinicia cada año '),
    sa.Column('DianResolution', sa.String(length=50), nullable=True, comment='Resolucion Dian '),
    sa.Column('IdSoftware', sa.String(length=100), nullable=True, comment='id software dian '),
    sa.Column('ClientNit', sa.String(length=20), nullable=True, comment='Nit del cliente '),
    sa.Column('ClientName', sa.String(length=100), nullable=True, comment='Nombre del cliente '),
    sa.Column('DateSend', sa.DateTime(timezone=10), nullable=True, comment='Fecha Envio '),
    sa.Column('HourSend', sa.String(length=20), nullable=True, comment='Hora Envio '),
    sa.Column('DianResponse', mysql.LONGTEXT(), nullable=True, comment='Respuesta DIAN '),
    sa.Column('DianResponseErrors', mysql.LONGTEXT(), nullable=True, comment='Errores DIAN '),
    sa.Column('DianXml', mysql.LONGTEXT(), nullable=True, comment='Xml enviado a DIAN '),
    sa.Column('DianXmlAppResponse', mysql.LONGTEXT(), nullable=True, comment='Xml Respuesta DIAN '),
    sa.Column('Cufe', sa.String(length=150), nullable=True, comment='CUFE, CUDE o CUNE documento '),
    sa.Column('TrackIdDian', sa.String(length=200), nullable=True, comment='Cadena que reporta la DIAN '),
    sa.Column('JsonReceived', mysql.LONGTEXT(), nullable=True, comment='JSON serializado'),
    sa.Column('MessageEmail', mysql.LONGTEXT(), nullable=True, comment='Mensaje del estado email'),
    sa.Column('Status', sa.String(length=1), nullable=True, comment='0 Rechazado 1=Enviado '),
    sa.Column('Total', sa.Float(precision=20), nullable=True, comment='total del documento'),
    sa.Column('IsCredit', sa.String(length=1), nullable=True, comment='0=No es credito 1=Es credito'),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index('ix_idy', 'shoppings', ['ReceiverNit', 'DocType', 'YearSend'], unique=False)
    op.add_column('events', sa.Column('DocumentNumberPerson', sa.String(length=20), nullable=True, comment='Numero de documento de la persona'))
    op.add_column('events', sa.Column('CheckDigitPerson', sa.String(length=1), nullable=True, comment='Digito de verificacion de la persona'))
    op.add_column('events', sa.Column('DocumentTypePerson', sa.String(length=5), nullable=True, comment='13=Cedula 31=NIT'))
    op.add_column('events', sa.Column('FirstNamePerson', sa.String(length=100), nullable=True, comment='Nombre de la persona'))
    op.add_column('events', sa.Column('LastNamePerson', sa.String(length=100), nullable=True, comment='Apellido de la persona'))
    op.add_column('events', sa.Column('JobTitle', sa.String(length=100), nullable=True, comment='Cargo del empleado'))
    op.add_column('events', sa.Column('OrganizationDepartment', sa.String(length=100), nullable=True, comment='Departamento de la empresa'))
    op.add_column('events', sa.Column('Note', mysql.LONGTEXT(), nullable=True, comment='Comentarios del evento'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'Note')
    op.drop_column('events', 'OrganizationDepartment')
    op.drop_column('events', 'JobTitle')
    op.drop_column('events', 'LastNamePerson')
    op.drop_column('events', 'FirstNamePerson')
    op.drop_column('events', 'DocumentTypePerson')
    op.drop_column('events', 'CheckDigitPerson')
    op.drop_column('events', 'DocumentNumberPerson')
    op.drop_index('ix_idy', table_name='shoppings')
    op.drop_table('shoppings')
    # ### end Alembic commands ###
