"""Campo

Revision ID: 1cfa81e3461b
Revises: e6395ab3533d
Create Date: 2022-06-01 14:45:54.674631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cfa81e3461b'
down_revision = 'e6395ab3533d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sendsinvoices', sa.Column('IsCredit', sa.String(length=1), nullable=True, comment='0=No es credito 1=Es credito'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sendsinvoices', 'IsCredit')
    # ### end Alembic commands ###
