"""Emails

Revision ID: 1e96c3e96e30
Revises: 1734ff01c2a0
Create Date: 2022-06-21 09:32:48.403012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e96c3e96e30'
down_revision = '1734ff01c2a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('CreateDate', sa.DateTime(), nullable=True, comment='Fecha de creación'),
    sa.Column('UpdateDate', sa.DateTime(), nullable=True, comment='Fecha de Modificación'),
    sa.Column('IssuerNit', sa.String(length=20), nullable=False, comment='Nit de la empresa o emisor '),
    sa.Column('Imap', sa.Text(), nullable=True, comment='Dirección de correo imap'),
    sa.Column('Key', sa.String(length=20), nullable=False, comment='Clave de acceso al correo'),
    sa.Column('Email', sa.String(length=100), nullable=True, comment='Email para recepcion de correos'),
    sa.Column('Port', sa.String(length=20), nullable=True, comment='Puerto para acceder al imap'),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('IssuerNit')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emails')
    # ### end Alembic commands ###
