"""IssuerName

Revision ID: 2349aea3331d
Revises: e1a4793b1d45
Create Date: 2022-08-27 10:20:01.912158

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2349aea3331d'
down_revision = 'e1a4793b1d45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('IssuerName', sa.String(length=200), nullable=False, comment='Nombre o razon social del emisor '))
    op.alter_column('invoices', 'AdditionalDocumentReferenceId',
               existing_type=mysql.VARCHAR(length=20),
               comment='numero de documento contingencia',
               existing_comment='numero de documento contingencia ',
               existing_nullable=True)
    op.alter_column('invoices', 'ProfileExecutionId',
               existing_type=mysql.VARCHAR(length=1),
               comment='tipo de ambiente 1=Produccion 2=Habilitacion',
               existing_comment='tipo de ambiente 1=Produccion 2=Habilitacion ',
               existing_nullable=False)
    op.add_column('notes', sa.Column('IssuerName', sa.String(length=200), nullable=False, comment='Nombre o razon social del emisor '))
    op.add_column('notessends', sa.Column('IssuerName', sa.String(length=200), nullable=False, comment='Nombre o razon social del emisor '))
    op.add_column('payrollsends', sa.Column('IssuerName', sa.String(length=200), nullable=False, comment='Nombre o razon social del emisor '))
    op.add_column('sendsinvoices', sa.Column('IssuerName', sa.String(length=200), nullable=False, comment='Nombre o razon social del emisor '))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sendsinvoices', 'IssuerName')
    op.drop_column('payrollsends', 'IssuerName')
    op.drop_column('notessends', 'IssuerName')
    op.drop_column('notes', 'IssuerName')
    op.alter_column('invoices', 'ProfileExecutionId',
               existing_type=mysql.VARCHAR(length=1),
               comment='tipo de ambiente 1=Produccion 2=Habilitacion ',
               existing_comment='tipo de ambiente 1=Produccion 2=Habilitacion',
               existing_nullable=False)
    op.alter_column('invoices', 'AdditionalDocumentReferenceId',
               existing_type=mysql.VARCHAR(length=20),
               comment='numero de documento contingencia ',
               existing_comment='numero de documento contingencia',
               existing_nullable=True)
    op.drop_column('events', 'IssuerName')
    # ### end Alembic commands ###
