"""Shoppings-IssuerNit

Revision ID: e1a4793b1d45
Revises: 1e96c3e96e30
Create Date: 2022-06-29 11:01:42.595614

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e1a4793b1d45'
down_revision = '1e96c3e96e30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shoppings', sa.Column('IssuerNit', sa.String(length=20), nullable=True, comment='Nit del cliente '))
    op.add_column('shoppings', sa.Column('IssuerName', sa.String(length=100), nullable=True, comment='Nombre del cliente '))
    op.drop_column('shoppings', 'ClientNit')
    op.drop_column('shoppings', 'ClientName')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shoppings', sa.Column('ClientName', mysql.VARCHAR(length=100), nullable=True, comment='Nombre del cliente '))
    op.add_column('shoppings', sa.Column('ClientNit', mysql.VARCHAR(length=20), nullable=True, comment='Nit del cliente '))
    op.drop_column('shoppings', 'IssuerName')
    op.drop_column('shoppings', 'IssuerNit')
    # ### end Alembic commands ###
