"""sends

Revision ID: e6395ab3533d
Revises: 04b6de18f1a6
Create Date: 2022-05-03 10:53:31.296100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6395ab3533d'
down_revision = '04b6de18f1a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notessends', sa.Column('Total', sa.Float(precision=20), nullable=True, comment='total del documento'))
    op.add_column('payrollsends', sa.Column('Accrued', sa.Float(precision=20), nullable=True, comment='total devengado'))
    op.add_column('payrollsends', sa.Column('Deducted', sa.Float(precision=20), nullable=True, comment='total deducido'))
    op.add_column('payrollsends', sa.Column('Value', sa.Float(precision=20), nullable=True, comment='diferencia devengado-deducido'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payrollsends', 'Value')
    op.drop_column('payrollsends', 'Deducted')
    op.drop_column('payrollsends', 'Accrued')
    op.drop_column('notessends', 'Total')
    # ### end Alembic commands ###
