"""token

Revision ID: f3c923842d14
Revises: e39406bbf072
Create Date: 2022-04-04 11:21:51.703847

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f3c923842d14'
down_revision = 'e39406bbf072'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('CreateDate', sa.DateTime(), nullable=True, comment='Fecha de creación'),
    sa.Column('UpdateDate', sa.DateTime(), nullable=True, comment='Fecha de Modificación'),
    sa.Column('CreateBy', sa.String(length=50), nullable=True),
    sa.Column('UpdateBy', sa.String(length=50), nullable=True),
    sa.Column('IsDeleted', mysql.TINYINT(display_width=1), nullable=True),
    sa.Column('ApiKey', sa.String(length=100), nullable=False, comment='Api Key de acceso'),
    sa.Column('ApiSecret', sa.String(length=100), nullable=False, comment='Api Secret de acceso '),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('ApiKey')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applications')
    # ### end Alembic commands ###
