trigger: none

variables:
  tag: '$(Build.BuildId)'
  branchName: '$(Build.SourceBranchName)'


# Stage 1
# Build backend
# Build Docker Images

stages:

- stage: Build
  displayName: Build Docker Images
  jobs:
  - job: Build_Backend
    displayName: Build Backend 
    pool:
      vmImage: 'ubuntu-18.04'
    steps:

    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'softpymesregistryconnector'
        repository: 'documents-backend'
        command: 'buildAndPush'
        Dockerfile: '$(System.DefaultWorkingDirectory)/compose/pro/Dockerfile'
        buildContext: $(System.DefaultWorkingDirectory)
        tags: '$(branchName)-$(tag)'

    - task: CopyFiles@2
      inputs:
        SourceFolder: $(System.DefaultWorkingDirectory)
        Contents: '**/*.yaml'
        TargetFolder: $(Build.ArtifactStagingDirectory)
    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'manifests'
        publishLocation: 'Container'

# Stage 2
# Download Ks8 Files
# Deploy to ks8 with docker image
- stage: Deploy
  displayName: Deploy image
  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'manifests'
        itemPattern: '**/*.yaml'
        downloadPath: '$(System.ArtifactsDirectory)'
    - task: KubernetesManifest@0
      inputs:
        action: 'deploy'
        kubernetesServiceConnection: 'aksclustertoolsconnector'
        namespace: 'production'
        manifests: '$(System.ArtifactsDirectory)/manifests/compose/pro/kubernetes/deploy.yaml'
        containers: 'softpymesregistry.azurecr.io/documents-backend:$(branchName)-$(tag)'
